use_frameworks!
target 'AnalyticsWatchAdapter' do
    pod 'GoogleAnalytics'
    pod 'AnalyticsWatchAdapter', :path => '../'
end
target 'AnalyticsWatchAdapterWatch Extension' do
    pod 'AnalyticsWatchAdapter', :path => '../'
end
